backend:
  name: github
  repo: michoux76/site # Path to your GitHub repository
  # optional, defaults to master
  # branch: main
media_folder: 'uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }